### ISSUE TITLE
TODO: various LMt based NLP improvements

### ISSUE THREAD

**Issue by PtrMan** [PtrMan/23R#11]
TASKS

- [x] disambiguate property with use of python NLP library  ex: parse "Tim is a fat cat" to ... <Tom --> {fat}> instead of <Tom --> fat>
   - [x] implement python script to disambiguate
   - [x] use python script from Nim code
   - [x] test it
- [x] use vicerna-13b for more complicated NLU task to break down complicated sentence (?)
   - [x] investigate if the 13b model is required to do so
   - [x] find new prompt
   - [x] implement parsing of result from LMt
   - [x] test it
