### ISSUE TITLE
TODO: add Persistent memory

### ISSUE THREAD

**Issue by PtrMan** [PtrMan/23R#7]
TASKS

- [ ] implement text serialization of term, tv, stamp
- [ ] implement text serialzation of memory
- [ ] add SqliteDb backend
- [ ] implement write
- [ ] implement load
